### ISSUE TITLE
Reversing the XC3020 on the Atari ST Atonce 386sx PC emulator

### ISSUE THREAD

**Issue by harbaum** [Arisotura/xc3000#1]
Thanks for releasing this interesting tool!

Over at the Atari forum someone took a closer look at the ATonce 386SX hardware emulator for the Atari ST. See
https://www.atari-forum.com/viewtopic.php?p=463583#p463583

He has rebuilt the PCB and has extracted the equations from the GAL to be able to rebuild the hardware. And the remake indeed seems to be working properly. There's also a XC3020 on that board, which does the heavy lifting in interfacing the 386sx CPU to the 68000 bus of the Atari ST. This FPGA is booted from a software running on the Atari ST, so knowing its details is not necessarily required to use the remade board. But as discussed in that thread, it might be possible to replace the 386sx CPU by a bigger modern FPGA running an HDL implementation of a 386 or even a 486. For that, it would be very useful to know the exact workings of the FPGA.

Someone else in that thread has extracted four bitstreams from the driver software:
https://www.atari-forum.com/viewtopic.php?p=464006#p464006

Your tool loads these files just fine and displays something that looks pretty promising (using e.g. BITREV4.BIN from aforementioned posting/zip);

![image](https://github.com/Arisotura/xc3000/assets/9105084/2d4fdf26-5683-466c-a9cb-bbd81e339809)

But a few things aren't clear. E.g. the CLB AA in that image. According to a right click on the CLB it contains the equations F=~B+E and G=~B+D. This CLB only has two inputs connected, but the equations use three. How do I interpret that? Also, some other CLBs use only output F or only output G, but graphically they use the same (bottom) output.

Could you please shed some light on this? It would be great if we could somehow use your tool (or another one) to get the equations back from the bitstream so we can replace the FPGA with a newer one while keeping compatibility with the existing software, or even replace the physical 386 CPU with an HDL core.

Thanks again!

**Comment by Arisotura** [comment]
It's possible that there's a bug in the decoding causing input AA.D to be missing. Could you provide a screenshot with the two debug checkboxes ('show all interconnects' and 'debug mode') checked?

It's also possible that there's an oversight in the bitstream. That's why I'd like to see the debug mode -- it will show if there's any interconnect that was missed.

"Also, some other CLBs use only output F or only output G, but graphically they use the same (bottom) output."

CLB outputs are ignored if nothing is connected to them.

The CLB outputs are, on the right, X (top) and Y (bottom). What they're connected to depends on the CLB configuration. They may be connected to logic outputs F or G, or to the outputs of the storage elements (QX and QY).

Coming back to AA up there, what does the diagram (when you right click) look like? It's possible that both X and Y may be connected to G, leaving F unused.

I thought the XC3-family datasheet had a reference of which inputs/outputs are which on the CLB, but I can't find it, so I drew a quick one:
![xc3clb](https://github.com/Arisotura/xc3000/assets/1311867/c08f0ccc-e750-4be2-a109-cfc3d5a94f4e)

Hoping that enlightens you!

**Comment by Arisotura** [comment]
PS: I actually went and downloaded these bitstreams so I could just have a look.

It appears that there's a bug somewhere, because there's a whole bunch of missing inputs on the left side. I'll look into it.

AA.E seems to be part of a pretty large net, so it will take me a while to find where the missing connection is.

**Comment by harbaum** [comment]
Excellent. Thanks a lot.

If G and F can be connected to either X or Y then how would I know which output X or Y is actually being connected to F and G? Is this also being displayed somewhere?

**Comment by Arisotura** [comment]
It's part of the info you see when you right-click the CLB.

Anyway, I fixed a bug with the clock lines. Doesn't fix the issue you reported, but that's one less. I'd built this tool while looking at XC3030 bitstreams -- the XC3 family members are all pretty similar, but the XC3020 has some differences and oddities, which I will need to look into further, it seems.

**Comment by harbaum** [comment]
That's awesome, thanks. There's a bunch of people watching this progressing. This kind of re-engineering is especially useful for these retro projects as they allow to document and preserve the old hardware.

**Comment by Arisotura** [comment]
I figure, heh.

I made a post on the forums but it's waiting for approval.

**Comment by Arisotura** [comment]
Well, I found it. Turns out that it was a bug that affected all XC3 family members.

![Screenshot 2024-05-20 at 19-27-39 XC3000 display](https://github.com/Arisotura/xc3000/assets/1311867/42938900-5181-4ab3-a935-4bf15cdbf27f)

It's connected to pin 15. There's also a bunch of other stuff connected to it.

This closes this issue, but don't hesitate to let me know if you run into more oddities.

**Comment by harbaum** [comment]
Excellent. I'll asap sit down and try to convert this to HDL. Should be interesting to see with actual signal names assigned

**Comment by Arisotura** [comment]
Good luck! Let me know if I could add any sort of utility to make this process easier.
